### ISSUE TITLE
Move to vfile organization?

### ISSUE THREAD

**Issue by ChristianMurphy** [vfile/vfile-reporter-folder-json#2]
Would there be interest in having this repository hosted out of the vfile organization @wooorm?

**Comment by wooorm** [comment]
Sure! 👍

**Comment by ChristianMurphy** [comment]
Cool, transferred repository.
Would it be possible to get [AppVeyor](https://appveyor.com/) and [Renovate](https://renovateapp.com/) switched back on for this repo? They get disabled during the transfer.

Are there any documentation or code changes that would help make this fit better with the vfile ecosystem practices?

**Comment by wooorm** [comment]
Oh right! Yeah, can you do that? Or do I need to do something for it?

> Are there any documentation or code changes that would help make this fit better with the vfile ecosystem practices?

* I suggest adding a license file in the repo
* could you add the contributing section, [like so](https://github.com/vfile/vfile-reporter#contribute) and license section, to readme?
* make sure to define [dependencies and dev-dependencies](https://github.com/vfile/vfile-reporter-folder-json/blob/048ea64fbe6463767585a7197669571ac3e83b88/package.json#L32), correctly, I don’t think this project has any dependencies?
* and that’s it, I think 🤷‍♂️

**Comment by ChristianMurphy** [comment]
> Oh right! Yeah, can you do that? Or do I need to do something for it?

Sure,
This is similar to https://github.com/remarkjs/grunt-remark/issues/35#issuecomment-358679419
Either an existing admin would need to switch this on, or I'd need to become an org admin.

---

Regarding the suggestions
1. Will do
2. Will do
3. Whoops I thought I had fixed that already :sweat_smile: you are correct only `devDependencies`

**Comment by ChristianMurphy** [comment]
Updates for 1, 2, and 3 have been added in.

**Comment by wooorm** [comment]
You’re an owner here on vfile (and also on remarkjs btw)!

**Comment by ChristianMurphy** [comment]
Thanks @wooorm!
